### ISSUE TITLE
Wrong CUB200 descriptors

### ISSUE THREAD

**Issue by FactoDeepLearning** [sachit-menon/classify_by_description_release#2]
Hello, thank you for this very interesting work.
It seems that the CUB200 descriptors are already formatted, contrary to the other dataset descriptors.
For instance:
    "Black-footed Albatross": [
        "It is a seabird.",
        "It is black and white.",
        "It has a long, hooked bill.",
        "It has long, narrow wings.",
        "It has black feet.",
        "It has a white head and neck."
    ]

This leads to inconsistent final descriptors such as 'Black-footed Albatross, which has It is a seabird..' 
with weird linking word between class and descriptor, and doubled final dot.

Could you please provide the correct descriptors for this dataset ?

**Comment by sachit-menon** [comment]
Hi, thanks for your interest and for catching the CUB formatting. I pushed a correction reformatting CUB to match the other ones, so it should work now. (The performance is a little bit better than initially reported in the paper, maybe I'll update that to match.)
