### ISSUE TITLE
The code for other datasets

### ISSUE THREAD

**Issue by XGGNet** [sachit-menon/classify_by_description_release#4]
Great Job! Could you please supply the data for using other datasets that you mentioned in your paper, besides CUB and imagenet? I want to evaluate the performance on more datasets, thank you.

**Comment by xuntianci** [comment]
Great Job! Could you please supply the data for using other datasets that you mentioned in your paper, besides CUB and imagenet? I want to evaluate the performance on more datasets, thank you.

**Comment by lr40** [comment]
Great Job! Could you please supply the data for using other datasets that you mentioned in your paper, besides CUB and imagenet? I want to evaluate the performance on more datasets, thank you.

**Comment by sachit-menon** [comment]
Hi, I added lines to load them and a pointer to the place to download them from, using VISSL -- that's what I used.
