### ISSUE TITLE
empty list of descriptors for 'donuts' in food-101

### ISSUE THREAD

**Issue by ltong1130ztr** [sachit-menon/classify_by_description_release#9]
https://github.com/sachit-menon/classify_by_description_release/blob/d1a3d8920af89bd0d6a692ed3afeb277df46e082/descriptors/descriptors_food101.json#L216

**Comment by sachit-menon** [comment]
Hi, this matches the results in the paper -- if the LLM produced nothing the category uses no descriptors. You could probably increase performance by resampling if that happens.
